spring:
  datasource:
    url: jdbc:mysql://localhost:3306/renewal_test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: T_renewal_test
    baseline-on-migrate: true
    version: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
