spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8080
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  metrics:
    tags:
      application: hufscheer-server

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml

---
spring:
  config:
    activate:
      on-profile: ci
    import: application-ci.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:be-config/application-prod.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:be-config/application-dev.yml
