spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트마다 스키마 재생성
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: false  # 테스트에서는 flyway 비활성화

# 테스트용 설정들 (local과 동일하게 유지)
report-check-origin: fake-origin.com
cors-allow-origins: http://localhost:3000

jwt:
  secret-key: test-secret
  valid-time: 604800

cookie:
  valid-time: 604800
  name: HCC_SES

amazon:
  aws:
    accessKey: test-access-key
    secretKey: test-secret-key
    region: ap-northeast-2
    bucket: test-bucket-name

image:
  origin-prefix: test-origin/
  replaced-prefix: test-replace/