spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0:///test_container_test
    username: root
    password: password
  flyway:
    locations: classpath:db/migration/dev
    table: flyway_test_schema_history
    sql-migration-prefix: T
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 10
report-check-origin: fake-origin.com
cors-allow-origins: http://localhost:3000

jwt:
  secret-key: secret
  valid-time: 604800 # 60 * 60 * 24 * 7 (일주일)

cookie:
  valid-time: 604800 # 60 * 60 * 24 * 7 (일주일)
  name: HCC_SES

amazon:
  aws:
    accessKey: access-key
    secretKey: secret-key
    region: ap-northeast-2
    bucket: bucket-name

image:
  origin-prefix: origin
  replaced-prefix: replace