spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0:///test_container_test
    username: root
    password: password
  jpa:
      hibernate:
        format_sql: true
        show_sql: true

report-check-origin: fake-origin.com
cors-allow-origins: http://localhost:3000
