= 훕치치 관객 서버 API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 응원톡 API

=== 응원톡 저장

operation::cheer-talk-controller-test/응원톡을_저장한다[snippets='http-request,request-fields,http-response']

=== 응원톡 조회

operation::cheer-talk-query-controller-test/응원톡을_조회한다[snippets='http-request,query-parameters,path-parameters,http-response,response-fields']

== 게임 API

=== 게임 상세 조회

operation::game-query-controller-test/게임을_상세_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 영상 조회

operation::game-query-controller-test/게임_영상_id를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 목록 조회

operation::game-query-controller-test/게임_목록을_조회한다[snippets='http-request,query-parameters,http-response,response-fields']

=== 게임 응원 횟수 조회

operation::game-query-controller-test/응원_횟수를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 라인업 조회

operation::game-query-controller-test/라인업을_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

== 라인업 API

=== 라인업 선수 선발로 변경

operation::game-controller-test/라인업_선수의_상태를_선발로_변경한다[snippets='path-parameters']

=== 라인업 선수 후보로 변경

operation::game-controller-test/라인업_선수의_상태를_후보로_변경한다[snippets='path-parameters']

== 응원 횟수 API

=== 응원 횟수 업데이트

operation::game-controller-test/응원_횟수를_업데이트한다[snippets='http-request,request-fields,http-response']

== 신고 API

=== 응원톡 신고

operation::report-controller-test/응원톡을_신고한다[snippets='http-request,request-fields,http-response']

== 리그 API

=== 리그 전체 조회

operation::league-query-controller-test/리그_전체를_조회한다[snippets='http-request,query-parameters,http-response,response-fields']

=== 리그에 해당하는 스포츠 전체 조회

operation::league-query-controller-test/리그의_해당하는_스포츠_전체를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 리그에 해당하는 리그팀 전체 조회

operation::league-query-controller-test/리그의_모든_리그팀을_라운드별로_조회한다[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

=== 리그팀 등록

operation::league-team-controller-test/리그팀을_등록한다[snippets='http-request,request-fields,http-response']

=== 리그 상세 조회

operation::league-query-controller-test/리그를_하나_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

== 타임라인 API

=== 득점 타임라인 생성
operation::timeline-controller-test/득점_타임라인을_생성한다[snippets='http-request,path-parameters,http-response']

=== 교체 타임라인 생성
operation::timeline-controller-test/교체_타임라인을_생성한다[snippets='http-request,path-parameters,http-response']

=== 게임의 타임라인 조회

operation::timeline-query-controller-test/타임라인을_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

== 스포츠 API

=== 스포츠 전체 조회

operation::sport-query-controller-test/스포츠를_전체_조회한다[snippets='http-request,http-response,response-fields']

== 로그인 API

=== 사용자 로그인

operation::auth-controller-test/로그인을_한다[snippets='http-request,request-fields,http-response']
