= 훕치치 서버 API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 응원톡 API

=== 응원톡 저장

operation::cheer-talk-controller-test/응원톡을_저장한다[snippets='http-request,request-fields,http-response']

=== 응원톡 조회

operation::cheer-talk-query-controller-test/응원톡을_조회한다[snippets='http-request,query-parameters,path-parameters,http-response,response-fields']

=== 신고된 리그의 응원톡 전체 조회

operation::cheer-talk-query-controller-test/리그의_신고된_응원톡을_조회한다[snippets='http-request,query-parameters,path-parameters,http-response,response-fields']

=== 응원톡 가리기

operation::cheer-talk-controller-test/응원톡을_가린다[snippets='http-request,path-parameters,http-response']

=== 응원톡을 가리기 취소하기

operation::cheer-talk-controller-test/응원톡을_가리기_취소한다[snippets='http-request,path-parameters,http-response']

=== 응원톡 관리 화면에서의 응원톡 전체 조회

operation::cheer-talk-query-controller-test/리그의_차단되지_않은_응원톡을_조회한다[snippets='http-request,query-parameters,path-parameters,http-response,response-fields']

== 게임 API

=== 게임 상세 조회

operation::game-query-controller-test/게임을_상세_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 영상 조회

operation::game-query-controller-test/게임_영상_id를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 목록 조회

operation::game-query-controller-test/게임_목록을_조회한다[snippets='http-request,query-parameters,http-response,response-fields']

=== 게임 응원 횟수 조회

operation::game-query-controller-test/응원_횟수를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 라인업 조회

operation::game-query-controller-test/라인업을_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 출전 선수 조회

operation::game-query-controller-test/출전_선수를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 게임 등록

operation::game-controller-test/경기를_등록한다[snippets='http-request,path-parameters,http-response']

=== 게임 수정

operation::game-controller-test/경기를_수정한다[snippets='http-request,path-parameters,http-response']

== 라인업 API

=== 라인업 선수 선발로 변경

operation::game-controller-test/라인업_선수의_상태를_선발로_변경한다[snippets='path-parameters']

=== 라인업 선수 후보로 변경

operation::game-controller-test/라인업_선수의_상태를_후보로_변경한다[snippets='path-parameters']

=== 라인업 선수 주장으로 등록

operation::game-controller-test/라인업_선수를_주장으로_등록한다[snippets='path-parameters']

=== 라인업 선수 주장에서 해제

operation::game-controller-test/라인업_선수를_주장에서_해제한다[snippets='path-parameters']

== 응원 횟수 API

=== 응원 횟수 업데이트

operation::game-controller-test/응원_횟수를_업데이트한다[snippets='http-request,request-fields,http-response']

== 신고 API

=== 응원톡 신고

operation::report-controller-test/응원톡을_신고한다[snippets='http-request,request-fields,http-response']

=== 응원톡 신고 무효처리(신고 취소)

operation::report-controller-test/신고된_응원톡을_무효처리한다[snippets='http-request,path-parameters,http-response']

== 리그 API

=== 리그 생성

operation::league-controller-test/리그를_생성한다[snippets='http-request,request-fields,http-response']

=== 리그 수정

operation::league-controller-test/리그를_수정한다[snippets='http-request,request-fields,http-response']

=== 리그 전체 조회

operation::league-query-controller-test/리그_전체를_조회한다[snippets='http-request,query-parameters,http-response,response-fields']

=== 리그에 해당하는 스포츠 전체 조회

operation::league-query-controller-test/리그의_해당하는_스포츠_전체를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 리그에 해당하는 리그팀 전체 조회

operation::league-query-controller-test/리그의_모든_리그팀을_라운드별로_조회한다[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

=== 리그에 해당하는 선수 전체 조회

operation::league-query-controller-test/리그팀의_모든_선수를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 리그팀 등록

operation::league-team-controller-test/리그팀을_등록한다[snippets='http-request,request-fields,http-response']

=== 리그팀 수정

operation::league-team-controller-test/리그팀을_수정한다[snippets='http-request,path-parameters,request-fields,http-response']

=== 리그팀 삭제

operation::league-team-controller-test/리그팀을_삭제한다[snippets='http-request,path-parameters,http-response']

=== 리그 상세 조회

operation::league-query-controller-test/리그를_하나_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 매니저가 생성한 리그 전체 조회(홈 화면)

operation::league-query-controller-test/매니저가_생성한_모든_리그와_진행중_경기를_조회한다[snippets='http-request,http-response,response-fields']

=== 매니저가 생성한 리그 전체 조회(대회 관리 화면)

operation::league-query-controller-test/매니저가_생성한_모든_리그를_조회한다[snippets='http-request,http-response,response-fields']

=== 리그 삭제

operation::league-controller-test/리그를_삭제한다[snippets='http-request,path-parameters,http-response']

=== 리그팀 상세 조회

operation::league-query-controller-test/리그팀을_상세_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 리그의 정보와 리그에 해당하는 경기 전체 조회

operation::league-query-controller-test/리그의_정보와_리그에_속한_모든_경기를_조회한다[snippets='http-request,http-response,response-fields']

== 타임라인 API

=== 득점 타임라인 생성

operation::timeline-controller-test/득점_타임라인을_생성한다[snippets='http-request,path-parameters,request-fields,http-response']

=== 교체 타임라인 생성

operation::timeline-controller-test/교체_타임라인을_생성한다[snippets='http-request,path-parameters,request-fields,http-response']

=== 게임 진행 타임라인 생성

operation::timeline-controller-test/게임_진행_변경_타임라인을_생성한다[snippets='http-request,path-parameters,request-fields,http-response']

=== 승부차기 타임라인 생성

operation::timeline-controller-test/게임_승부차기_타임라인을_생성한다[snippets='http-request,path-parameters,request-fields,http-response']

=== 게임의 타임라인 조회

operation::timeline-query-controller-test/타임라인을_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== 타임라인 삭제

operation::timeline-controller-test/타임라인을_삭제한다[snippets='http-request,request-cookies,path-parameters,http-response']

== 스포츠 API

=== 스포츠 전체 조회

operation::sport-query-controller-test/스포츠를_전체_조회한다[snippets='http-request,http-response,response-fields']

== 사용자 API

=== 사용자 로그인

operation::auth-controller-test/로그인을_한다[snippets='http-request,request-fields,http-response']

=== 사용자 정보 조회

operation::sport-query-controller-test/스포츠를_전체_조회한다[snippets='http-request,http-response,response-fields']
