ALTER TABLE teams ADD COLUMN organization_id BIGINT NULL;
ALTER TABLE teams ADD CONSTRAINT FK_TEAMS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE players ADD COLUMN organization_id BIGINT NULL;
ALTER TABLE players ADD CONSTRAINT FK_PLAYERS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);
