ALTER TABLE cheer_talks MODIFY COLUMN game_team_id BIGINT NULL;
ALTER TABLE cheer_talks DROP FOREIGN KEY FK_CHEER_TALKS_ON_GAME_TEAMS;
ALTER TABLE cheer_talks ADD CONSTRAINT FK_CHEER_TALKS_ON_GAME_TEAMS FOREIGN KEY (game_team_id) REFERENCES game_teams (id) ON DELETE SET NULL;
