ALTER TABLE timelines
    DROP FOREIGN KEY FK_TIMELINES_ON_GAME;

ALTER TABLE timelines
    ADD CONSTRAINT FK_TIMELINES_ON_GAME FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE timelines
DROP FOREIGN KEY FK_TIMELINES_ON_ORIGIN_LINEUP_PLAYER;

ALTER TABLE timelines
    ADD CONSTRAINT FK_TIMELINES_ON_ORIGIN_LINEUP_PLAYER FOREIGN KEY (origin_lineup_player_id) REFERENCES lineup_players(id) ON DELETE CASCADE;

ALTER TABLE timelines
DROP FOREIGN KEY FK_TIMELINES_ON_REPLACED_LINEUP_PLAYER;

ALTER TABLE timelines
    ADD CONSTRAINT FK_TIMELINES_ON_REPLACED_LINEUP_PLAYER FOREIGN KEY (replaced_lineup_player_id) REFERENCES lineup_players(id) ON DELETE CASCADE;

ALTER TABLE timelines
DROP FOREIGN KEY FK_TIMELINES_ON_SCORER;

ALTER TABLE timelines
    ADD CONSTRAINT FK_TIMELINES_ON_SCORER FOREIGN KEY (scorer_id) REFERENCES lineup_players(id) ON DELETE CASCADE;
